name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          base-devel
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gdb
          mingw-w64-x86_64-libelf
          mingw-w64-x86_64-libepoxy
          mingw-w64-x86_64-libzip
          mingw-w64-x86_64-lua
          mingw-w64-x86_64-pkgconf
          mingw-w64-x86_64-qt5
          mingw-w64-x86_64-qt5-tools
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-ntldd-git
          mingw-w64-x86_64-ffmpeg
          mingw-w64-x86_64-ninja

    - name: Configure
      shell: msys2 {0}
      run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$PWD/build/install"

    - name: Build
      shell: msys2 {0}
      run: cmake --build build --config Release

    - name: Collect runtime DLLs
      shell: msys2 {0}
      run: |
        set -e
        cmake --install build --config Release
        appdir="$PWD/build/install"
        qt_exe="$appdir/mGBA.exe"
        if [ -f "$qt_exe" ]; then
          /mingw64/bin/windeployqt.exe --no-translations --release --dir "$appdir" "$qt_exe" || true
        fi
        mapfile -t bins < <(find "$appdir" -maxdepth 1 -type f \( -iname '*.exe' -o -iname '*.dll' \))
        for bin in "${bins[@]}"; do
          ntldd -R "$bin" | sed -n 's/.*=> \(.*\) (0x[0-9a-fA-F]\+)/\1/p' | while read -r dep; do
            [ -z "$dep" ] && continue
            dep_unix=$(cygpath -u "$dep" 2>/dev/null || true)
            [ -z "$dep_unix" ] && continue
            case "$dep_unix" in
              /mingw64/bin/*) cp -u "$dep_unix" "$appdir/";;
            esac
          done
        done

    - name: Package
      shell: msys2 {0}
      run: |
        cmake -E chdir build/install cmake -E tar cf ../mgba-windows.zip --format=zip .

    - name: Upload distribution package
      uses: actions/upload-artifact@v4
      with:
        name: mgba-windows-distribution
        path: build/mgba-windows.zip
        retention-days: 14
